import '/colors_and_type.css'
import './styles/global.css'
import './styles/common.css'
import './styles/ui.css'
import './styles/workspace.css'
import './styles/shell.css'
import './styles/kg.css'
import './styles/navigator.css'
import './styles/findings.css'
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
ReactDOM.createRoot(document.getElementById('root')).render(<App />)
